- name: "sandbox | Create {{workspace}}/modules/{{ module }}/docker/.build"
  file:
    path: "{{workspace}}/modules/{{ module }}/docker/.build"
    state: directory
    recurse: yes

- name: 'sandbox | Copy sepal-ee'
  synchronize:
    src: "{{ module_dir }}/../google-earth-engine/docker/sepal-ee"
    dest: "{{workspace}}/modules/{{ module }}/docker/.build/"
    archive: yes
    recursive: yes
    delete: yes

- include_tasks: "{{ build_image_task }}"
